name: daunused
description: A Dart package that checks for unused files in your project.
version: 1.8.0
homepage: https://github.com/mauriciotogneri/daunused

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  analyzer: ^9.0.0
